CREATE TABLE products (
  id int(11) NOT NULL AUTO_INCREMENT,
  name varchar(4000) NOT NULL,
  price decimal(15,2) NOT NULL,
  quantity int NOT NULL,
  picture varchar(4000),
  description varchar(4000),
  PRIMARY KEY (id)
);


insert into products (name, price, quantity, picture, description) values ('Xiaomi Mi 34" curved gaming monitor', 4990, 1, 'https://www.elgiganten.se/image/dv_web_D180001002532918/202554/xiaomi-mi-34-curved-gaming-monitor--pdp_zoom-3000--pdp_main-960.jpg', 'Xiaomi Mi 34" curved gaming monitor will envelop you in amazing visuals whether you are gaming or watching movies. Thanks to the crisp WQHD resolution, 144 Hz refresh rate, and 4 ms response time nothing will stand in your way while gaming online.');
insert into products (name, price, quantity, picture, description) values ('LG UltraGear 27GP850 27" bildskärm för gaming', 4495, 3, 'https://www.elgiganten.se/image/dv_web_D180001002786663/327232/lg-ultragear-27gp850-27-bildskarm-for-gaming--pdp_zoom-3000--pdp_main-960.jpg', 'LG UltraGear 27GP850 27" bildskärm för gaming ger liv åt dina spelbilder tack vare QHD Nano IPS-panelen med 98% DCI-P3 färgspektrum och HD400-standard. Du får otroligt smidiga rörelser med 165 Hz uppdateringsfrekvens och 1 ms responstid.');
insert into products (name, price, quantity, picture, description) values ('Asus TUF Gaming VG24VQE 24" bildskärm för gaming', 1990, 1, 'https://www.elgiganten.se/image/dv_web_D180001002732256/304890/asus-tuf-gaming-vg24vqe-24-bildskarm-for-gaming--pdp_zoom-3000--pdp_main-960.jpg', 'Asus TUF Gaming VG24VQE 24" bildskärm för gaming ger dig en snabb uppdateringsfrekvens på 165 Hz och en responstid på endast 1 ms, för du ska kunna förvandla dina snabba reflexer till följsamma rörelser på skärmen.');
insert into products (name, price, quantity, picture, description) values ('SteelSeries Arctis 7 Plus Wireless headset för gaming (svart)', 2049, 2, 'https://www.elgiganten.se/image/dv_web_D180001002875101/390484/steelseries-arctis-7-plus-wireless-headset-for-gaming-svart--pdp_zoom-3000--pdp_main-960.jpg', 'SteelSeries Arctis 7 Plus Wireless gamingheadset är för spelare som vill ha fantastiskt ljud som han eller hon kan använda på alla sina spelenheter.');
insert into products (name, price, quantity, picture, description) values ('Razer Kraken Kitty Gaming Headset, Wired, Svart', 1579, 10, 'https://www.elgiganten.se/image/dv_web_D180001002825645/357355/razer-kraken-kitty-gaming-headset-wired-svart--pdp_zoom-3000--pdp_main-960.jpg', 'Andra funktioner: Kitty-öron och öronkåpor som drivs av Razer Chroma, strömreaktiv belysning, aktiv brusreducerande mikrofon, THX Spatial Audio, kylande gel-öronkuddar Frekvenssvar: 20 - 20000 Hz Impedans: 32 Ω Känslighet: 109 dBmW.');
insert into products (name, price, quantity, picture, description) values ('Razer BlackShark V2 Pro gamingheadset (vitt)', 1999, 5, 'https://www.elgiganten.se/image/dv_web_D180001002826389/352532/razer-blackshark-v2-pro-gamingheadset-vitt--pdp_zoom-3000--pdp_main-960.jpg', 'Razer BlackShark V2 Pro gaming headset hjälper dig att vinna genom en fantastisk ljudupplevelse. Headsetet kommer med 50 mm TriForce Titanium membran och THX Spatial Audio samt en HyperClear Supercardioid mikrofon så hela teamet hör dig.');
insert into products (name, price, quantity, picture, description) values ('Razer Basilisk Ultimate gamingmus', 1799, 3, 'https://www.elgiganten.se/image/dv_web_D180001002754210/320201/razer-basilisk-ultimate-gamingmus--pdp_zoom-3000--pdp_main-960.jpg', 'Razer Basilisk Ultimate gamingmus är det ultimata vapnet för varje viktig strid. Den har Razer Focus+ optisk sensor med 20 000 DPI och Razer optisk switch.');
insert into products (name, price, quantity, picture, description) values ('SteelSeries Aerox 3 Wireless gamingmus 2022 Edition (Onyx)', 1199, 2, 'https://www.elgiganten.se/image/dv_web_D180001002878221/390487/steelseries-aerox-3-wireless-gamingmus-2022-edition-onyx--pdp_zoom-3000--pdp_main-960.jpg', 'SteelSeries Aerox 3 trådlös gamingmus 2022 Edition ger dig en blandning av hastighet, noggrannhet ochrörlighet, då den inte begränsas av irriterande kablar utan låter dig röra dig fritt.');
insert into products (name, price, quantity, picture, description) values ('Next SR7 gamingmus (vit)', 199, 4, 'https://www.elgiganten.se/image/dv_web_D180001002801251/341560/next-sr7-gamingmus-vit--pdp_zoom-3000--pdp_main-960.jpg', 'Next SR7 gamingmus har optisk sensor, justerbar känslighet och pålitlig anslutning. Musen har vaxkakedesign och väger bara 78 gram. Med en optisk sensor får du snabb precision och 7200 DPI till ditt förfogande. Använd den särskilda DPI-knappen för att ändra känsligheten i farten. Spela med stil tack vare RGB-belysningen som kan justeras med en dedikerad knapp.');